import { createClerkSupabaseClient } from '@/lib/supabase';
import { NextRequest, NextResponse } from 'next/server';

/**
 * POST: Create a new student with enrollment in Supabase
 * StudentID and EnrollmentID are auto-generated via UUID and sequences
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { userId, courseId, intake } = body;

    // Validation
    if (!userId || !courseId || !intake) {
      return NextResponse.json(
        { error: 'Missing required fields: userId, courseId, intake' },
        { status: 400 }
      );
    }

    const supabase = await createClerkSupabaseClient();

    // Create student record (StudentID auto-generated as UUID, StudentCode auto-generated by sequence)
    const { data: studentData, error: studentError } = await supabase
      .from('Student')
      .insert([
        {
          UserID: userId,
          // StudentID will be auto-generated as UUID by Supabase
          // StudentCode will be auto-generated as STU000001, STU000002, etc. by the sequence
        },
      ])
      .select()
      .single();

    if (studentError) throw studentError;

    if (!studentData?.StudentID) {
      throw new Error('Student ID was not generated');
    }

    // Create enrollment record (EnrollmentID auto-generated as UUID by Supabase)
    const { data: enrollmentData, error: enrollmentError } = await supabase
      .from('Enrollment')
      .insert([
        {
          StudentID: studentData.StudentID,
          CourseID: courseId,
          Intake: intake,
          Balance: 0, // Auto-set to 0
          // EnrollmentID will be auto-generated as UUID by Supabase
          // WalletID might be auto-generated depending on your DB setup
        },
      ])
      .select()
      .single();

    if (enrollmentError) throw enrollmentError;

    return NextResponse.json({
      success: true,
      student: studentData,
      enrollment: enrollmentData,
    });
  } catch (error: any) {
    console.error('Error creating student:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to create student' },
      { status: 500 }
    );
  }
}